[project]
name = "argus"
version = "0.0.0"  # refer to argus/__init__.py for the actual version
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx[socks]>=0.28.1",
    "numpy==2.5.3",
    "pandas==3.0.5",
    "pandas-stubs~=3.0.3",
    "py-clob-client-v2==1.1.0",
    "python-dotenv==1.2.3",
    "python-socks==3.1.1",
    "requests==2.34.2",
    "selenium==4.49.0",
    "setuptools==84.0.0",
    "termcolor>=3.3.0",
    "tqdm==4.70.0",
    "utils3",
    "websocket-client==1.9.2",
    "websockets==17.1",
]

[tool.uv.sources]
utils3 = { git = "https://github.com/the-sal/utils3" }
